### ISSUE TITLE
Is there any Discord or Forum to get some help?

### ISSUE THREAD

**Issue by Assambra** [youngmonkeys/ezyfox-server-archetype#9]
Is there any Discord or Forum to get some help?

i have some questions or some problems:

Ive created a Create Account function that can be create a new Account in the mongodb and send back the result. But at the moment i use the normal Login with Guest Guest and some bypass on the serverside if both match it will be logged in so that i can communicate with the server to create the new Account.

Question: Is there any function to communicate to the server without a successfully loged in user? Or something like a guest login? Or do i need a seperate Zone or what is the best solution to handle the problem?

There are some following problems too, lets say some pre or without a login to handle check server client version , or check server online or in maintainance state.

I use te CSharp Unity client plugin:
Question: How to check if there is a active connection?
Question: How to disconnect a active connection and cloase the socket from client side? 
Question: How to create a persistent MMO Scene (Main World)? The EzySmashers example only have a lobby based and "Team roomes" example. Maybe i can use this for create runtime mmo roomes for Team instanced rooms like Dungeons or Raid instance for teams.

if some one want grab a copy of the project and maybe want to help:
Project: https://github.com/Assambra/Free-MMORPG  Branch: [feature/Account](https://github.com/Assambra/Free-MMORPG/tree/feature/Account)
Issue: https://github.com/Assambra/Free-MMORPG/issues/2
Or join me on Discord: https://discord.gg/KJHTkb36

Thanks in advance

**Comment by tvd12** [comment]
Could you create question here https://stackask.com/ ?

**Comment by tvd12** [comment]
You will have options:

1. Create a zone for guest to register like you said.
2. Create a HTTP server (you can use ezyhttp) and provide register API.

I think you should choose option 2nd, because create a zone for guest is a not good idea for security.
